### ISSUE TITLE
On-demand interest profiles during the evaluation period

### ISSUE THREAD

**Issue by lintool** [trecrts/trecrts.github.io#3]
Question is: will participant systems get to submit new interest profiles during the evaluation period? That is, programmatically via an API to the evaluation broker.

Answer is: we're leaning to **NO**

We anticipate that there may be new interest profiles that are added _during_ the evaluation period, but these will be added by the organizers (of course, you are welcome to suggestion new interest profiles to us over email), but we (in consultation with NIST, of course) will be the only ones to add new interest profiles to the evaluation.

This will likely be via some type of API, where the participants will poll for new interest profiles. To avoid excessive polling, we'll likely agree ahead of time that new interest profiles will only start at the beginning of each day (or some other known starting time), so that participating systems will not need to poll the broker repeatedly.

Thoughts?

**Comment by lintool** [comment]
Per Ellen's directive from NIST, we need to start nailing down the guidelines concretely. Unless we hear any more discussion before (Friday) April 29 - this will be the plan.

**Comment by cbuntain** [comment]
I like the idea of dynamic interest profiles that respond to events of the day. My work is designed for scenarios where impactful events occur, and you want to track new developments, so having a more responsive mechanism for generating interest profiles would be more consistent with my approach. Dynamic interest profiles could be provided either way (participants vs. TREC organizers/NIST), and while I have no _major_ preference between them, it might be interesting to have participants submit interest profiles as an additional task. Think of it like open-domain summarization? 

As further justification of participant-submitted profiles as an alternate task, it occurs to me that allowing participant-submitted interest profiles that would be treated identically to NIST-provided ones may really blow up the number of necessary evaluations. Given that we are already resource-constrained in evaluations, making that more difficult by adding possibly many more topics and tweets to be evaluated would not be worthwhile. Evaluating submitted submitted interest profiles without tweets could still be interesting as a sort of headline generation mechanism, but this may not be sufficiently inline with the RTS track's goals.

**Comment by lintool** [comment]
Yes, participants could also suggest new profiles (e.g., over email, but otherwise out of band wrt eval framework) - it will be the discretion of NIST (primarily) whether these will become "official" topics.

**Comment by xeniaqian94** [comment]
Under the Automatic Runs last year, it seems that processing on the profiles will be allowed after participants polled the profile and before the evaluation period. For dynamically updated profiles, will there be a fixed "poll" time (say, at noon) and also a fixed "start" time (say, at the beginning of the next day)?

**Comment by lintool** [comment]
The current plan is that new topics will only start at the beginning of each day, i.e., 00:00:00 UTC. This is so that systems won't have to repeatedly poll the evaluation broker.

**Comment by xeniaqian94** [comment]
Thanks. Then system design might still need to tackle how "responsive" a system is to new topics, the sooner it is able to process the interest profile, the sooner it is able to start pushing...?

**Comment by lintool** [comment]
Hi Xin, I'm not sure I understand your comment fully. Yes, systems will be responsible for periodically polling the evaluation broker to get new topics and then process accordingly.

**Comment by xeniaqian94** [comment]
Thanks Jimmy. Got it, therefore, periodically poll the evaluation broker throughout the day to get new topics, process on interest profiles immediately afterwards (usually finished in minutes), sleep till a new day starts to start the new topics.

**Comment by lintool** [comment]
It's up to each team on how to handle it, but yes, that would be a good strategy.

**Comment by lintool** [comment]
It's settled!
