### ISSUE TITLE
TREC evaluation broker load testing

### ISSUE THREAD

**Issue by lintool** [trecrts/trecrts.github.io#5]
@richardmcc says that Glasgow has a tweet stream replay system that can be used to load test the TREC evaluation broker. We will need to do this at some point in time.

**Comment by cbuntain** [comment]
I put together a similar replay system available here: https://github.com/cbuntain/replayTweetStream. It can send to TCP or console, and I've used it with Spark's streaming API in the past. Glasglow's may be more mature though.

**Comment by lintool** [comment]
Closing issue. TREC 2016 over! Reshuffling deck for TREC 2017.
